### PR TITLE
spike: Test bigger framebuffer

### PR DESCRIPTION
**Pull request by sbernauer**
Works in general, but for **whatever** reason
```
time:   [31.504 ms 31.558 ms 31.611 ms]
change: [+25.068% +25.395% +25.712%] (p = 0.00 < 0.05)
Performance has regressed.
```
Was also able to reproduce this looking at traffic levels and pixelflut client
CC @fabi321

### CODE REVIEW

**Comment by fabi321** [comment]
If I run the server with this change, it is slightly faster (15Gbit/s compared to 16Gbit/s), but the bench is within noise level for me. I'm not sure, whether the real world improvement is due to broken vnc server support.

**Comment by sbernauer** [comment]
Absolute agreed!
Would you be fine with closing this?

**Comment by fabi321** [comment]
sure, go ahead.

**Comment by sbernauer** [comment]
Alright, was a good idea I would say but yeah

**Pull request closed without merging**
