### PR TITLE
simd digit parsing

### PR DESCRIPTION
**Pull request by fabi321**
As the performance is currently worse than the performance of the existing solution (at least on my machine), this is only a draft.

### CODE REVIEW

**Comment by fabi321** [comment]
My suspicion is that the array lookup is slowing it down, but I haven't found a way yet to efficiently compute it on the fly.

**Comment by sbernauer** [comment]
I did also try out something in https://github.com/sbernauer/breakwater/pull/10.
Haven't optimized, but pretty slow currently :(
Happy about any feedback

**Comment by fabi321** [comment]
I'm giving up on this. I'll leave the branch up as educational resource, but given that I can't even beat the worst case performance of the other solution, let a lone get near the best case performance, I don't think that it's possible to be faster by eliminating jumps.

My current solution doesn't even have array lookups (one part that I suspected might eat some performance). I was kinda hoping that doing stuff in parallel would magically lift the obvious factor, that you'll end up processing way more data, best or worst case. But it looks like doing more stuff also leads to worse performance, even if you do use all of the processors features.

**Comment by sbernauer** [comment]
I absolutely know your pain! Totally relate

**Pull request closed without merging**
